<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Try except on Christian Barra</title>
    <link>http://chrisbarra.xyz/tags/try-except/</link>
    <description>Recent content in Try except on Christian Barra</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    <lastBuildDate>Fri, 03 Nov 2017 00:00:00 +0000</lastBuildDate>
    
	<atom:link href="http://chrisbarra.xyz/tags/try-except/index.xml" rel="self" type="application/rss+xml" />
    
    
    <item>
      <title>The code review that never happened</title>
      <link>http://chrisbarra.xyz/posts/the-code-review-that-never-happened/</link>
      <pubDate>Fri, 03 Nov 2017 00:00:00 +0000</pubDate>
      
      <guid>http://chrisbarra.xyz/posts/the-code-review-that-never-happened/</guid>
      <description>I am currently working as consultant for a mid-sized company in Europe, where my goal is to try to keep their old Django application alive (running Django 1.5.5).

A few weeks ago, it became clear to me that the server running the application was down. Something wasn&amp;rsquo;t working properly, and yet the logs were completely silent.

So I said… well, there must be an except: pass somewhere and I started looking for it (so much for my Friday night…)</description>
    </item>
    
  </channel>
</rss>